import React from 'react';
import { Link } from 'react-router-dom';

import { accountingUrl, adminUrl, apiFetch, formatCurrency } from '../config/api';

import './admin.css';

const AdminDashboard = () => {
  const [overview, setOverview] = React.useState(null);
  const [revenue, setRevenue] = React.useState(0);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    Promise.all([
      apiFetch(adminUrl('/integration-overview')),
      apiFetch(accountingUrl('/invoices')),
    ])
      .then(([overviewPayload, invoicePayload]) => {
        setOverview(overviewPayload);
        const totalRevenue = (invoicePayload.items || []).reduce(
          (sum, invoice) => sum + Number(invoice.grand_total || 0),
          0
        );
        setRevenue(totalRevenue);
        setLoading(false);
      })
      .catch((error) => {
        console.error(error);
        setLoading(false);
      });
  }, []);

  const counts = overview?.counts || {};
  const latest = overview?.latest || {};

  return (
    <div className="admin-page">
      <div className="admin-page-header">
        <h2 className="admin-page-title">Dashboard Overview</h2>
        <p className="admin-page-subtitle">Live view of the integration stack behind WatchCommerce.</p>
      </div>

      {loading ? (
        /* Loading Skeleton State */
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '24px', marginBottom: '32px' }}>
          <div className="admin-card admin-skeleton admin-skeleton-card" style={{ border: 'none' }}></div>
          <div className="admin-card admin-skeleton admin-skeleton-card" style={{ border: 'none' }}></div>
          <div className="admin-card admin-skeleton admin-skeleton-card" style={{ border: 'none' }}></div>
        </div>
      ) : (
        /* Actual Metric Cards Grid */
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '24px', marginBottom: '32px' }}>
          <div className="admin-card">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <span style={{ fontSize: 'var(--admin-font-label-caps)', color: 'var(--admin-text-secondary)', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.15em' }}>Total Revenue</span>
              <span className="material-symbols-outlined" style={{ color: 'var(--admin-primary)', fontSize: '24px' }}>payments</span>
            </div>
            <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--admin-text-primary)', fontFamily: 'var(--admin-font-display)' }}>
              {formatCurrency(revenue)}
            </div>
            <div style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-text-muted)', marginTop: '12px', lineHeight: '1.4' }}>
              Sum of invoices generated by the accounting service database.
            </div>
          </div>

          <div className="admin-card">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <span style={{ fontSize: 'var(--admin-font-label-caps)', color: 'var(--admin-text-secondary)', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.15em' }}>Active Orders</span>
              <span className="material-symbols-outlined" style={{ color: 'var(--admin-primary)', fontSize: '24px' }}>shopping_cart</span>
            </div>
            <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--admin-text-primary)', fontFamily: 'var(--admin-font-display)' }}>
              {counts.orders || 0}
            </div>
            <div style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-text-muted)', marginTop: '12px', lineHeight: '1.4' }}>
              Includes all client checkouts persisted by `order-api`.
            </div>
          </div>

          <div className="admin-card">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <span style={{ fontSize: 'var(--admin-font-label-caps)', color: 'var(--admin-text-secondary)', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.15em' }}>Low Stock Items</span>
              <span className="material-symbols-outlined" style={{ color: 'var(--admin-error)', fontSize: '24px' }}>warning</span>
            </div>
            <div style={{ fontSize: '2rem', fontWeight: '800', color: 'var(--admin-error)', fontFamily: 'var(--admin-font-display)' }}>
              {overview?.inventory?.low_stock_items?.length || 0}
            </div>
            <div style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-text-muted)', marginTop: '12px', lineHeight: '1.4' }}>
              Timepieces with inventory count below the safe threshold of 10.
            </div>
          </div>
        </div>
      )}

      {loading ? (
        /* Snapshot Skeleton */
        <div className="admin-card admin-skeleton" style={{ minHeight: '320px', border: 'none' }}></div>
      ) : (
        /* Integration Snapshot Section */
        <div className="admin-card" style={{ padding: '32px' }}>
          <h3 style={{ fontFamily: 'var(--admin-font-display)', fontSize: '1.25rem', fontWeight: '700', marginBottom: '24px', letterSpacing: '-0.01em', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span className="material-symbols-outlined" style={{ color: 'var(--admin-primary)' }}>sync_alt</span>
            Latest Integration Snapshot
          </h3>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '20px', marginBottom: '32px' }}>
            <div style={{ padding: '16px 20px', backgroundColor: 'var(--admin-bg-surface-hover)', borderRadius: '12px', border: '1px solid var(--admin-border)' }}>
              <div style={{ fontSize: 'var(--admin-font-label-caps)', color: 'var(--admin-text-secondary)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '8px' }}>Inventory Reservations</div>
              <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--admin-text-primary)' }}>{counts.inventory_reservations || 0}</div>
            </div>

            <div style={{ padding: '16px 20px', backgroundColor: 'var(--admin-bg-surface-hover)', borderRadius: '12px', border: '1px solid var(--admin-border)' }}>
              <div style={{ fontSize: 'var(--admin-font-label-caps)', color: 'var(--admin-text-secondary)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '8px' }}>Invoices Created</div>
              <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--admin-text-primary)' }}>{counts.invoices || 0}</div>
            </div>

            <div style={{ padding: '16px 20px', backgroundColor: 'var(--admin-bg-surface-hover)', borderRadius: '12px', border: '1px solid var(--admin-border)' }}>
              <div style={{ fontSize: 'var(--admin-font-label-caps)', color: 'var(--admin-text-secondary)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '8px' }}>CRM Purchases Synced</div>
              <div style={{ fontSize: '1.5rem', fontWeight: '700', color: 'var(--admin-text-primary)' }}>{counts.crm_purchases || 0}</div>
            </div>
          </div>

          {latest.order ? (
            <div style={{ padding: '24px', backgroundColor: 'rgba(212, 175, 55, 0.03)', borderRadius: '12px', border: '1px solid rgba(212, 175, 55, 0.15)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px' }}>
              <div>
                <span style={{ fontSize: 'var(--admin-font-label-caps)', color: 'var(--admin-primary)', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Newest Order</span>
                <h4 style={{ fontFamily: 'var(--admin-font-display)', fontSize: '1.15rem', color: 'var(--admin-text-primary)', margin: '4px 0' }}>
                  Order #{latest.order.id} &middot; {latest.order.customer_name}
                </h4>
                <p style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-text-secondary)', margin: 0 }}>
                  Customer Email: {latest.order.customer_email}
                </p>
              </div>
              <div style={{ textAlign: 'right' }}>
                <div style={{ fontSize: '1.3rem', fontWeight: '700', color: 'var(--admin-text-primary)' }}>
                  {formatCurrency(latest.order.total_amount)}
                </div>
                {latest.invoice && (
                  <Link to="/admin/sales" className="admin-btn-primary" style={{ display: 'inline-block', marginTop: '12px', textDecoration: 'none', fontSize: '10px', padding: '6px 14px' }}>
                    View Sales Details
                  </Link>
                )}
              </div>
            </div>
          ) : (
            <div style={{ padding: '24px', textAlign: 'center', color: 'var(--admin-text-muted)' }}>
              No orders or snapshots recorded in the database.
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default AdminDashboard;
