import React from 'react';
import { Link } from 'react-router-dom';

import { accountingUrl, adminUrl, apiFetch, formatCurrency } from '../config/api';

import './admin.css';

const AdminDashboard = () => {
  const [overview, setOverview] = React.useState(null);
  const [revenue, setRevenue] = React.useState(0);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    Promise.all([
      apiFetch(adminUrl('/integration-overview')),
      apiFetch(accountingUrl('/invoices')),
    ])
      .then(([overviewPayload, invoicePayload]) => {
        setOverview(overviewPayload);
        const totalRevenue = (invoicePayload.items || []).reduce(
          (sum, invoice) => sum + Number(invoice.grand_total || 0),
          0
        );
        setRevenue(totalRevenue);
        setLoading(false);
      })
      .catch((error) => {
        console.error(error);
        setLoading(false);
      });
  }, []);

  const counts = overview?.counts || {};
  const latest = overview?.latest || {};

  return (
    <div className="admin-page">
      <div className="admin-page-header">
        <h2 className="admin-page-title">Dashboard Overview</h2>
        <p className="admin-page-subtitle">Live view of the integration stack behind WatchCommerce.</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '24px', marginBottom: '32px' }}>
        <div style={{ backgroundColor: 'var(--admin-surface)', padding: '24px', borderRadius: '16px', border: '1px solid var(--admin-outline-variant)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
            <span style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-on-surface-variant)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.15em' }}>Total Revenue</span>
            <span className="material-symbols-outlined" style={{ color: 'var(--admin-primary)' }}>payments</span>
          </div>
          <div style={{ fontSize: '32px', fontWeight: '700', color: 'var(--admin-primary)' }}>{formatCurrency(revenue)}</div>
          <div style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-on-surface-variant)', marginTop: '8px' }}>
            Sum of invoice grand totals generated by accounting service.
          </div>
        </div>

        <div style={{ backgroundColor: 'var(--admin-surface)', padding: '24px', borderRadius: '16px', border: '1px solid var(--admin-outline-variant)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
            <span style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-on-surface-variant)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.15em' }}>Active Orders</span>
            <span className="material-symbols-outlined" style={{ color: 'var(--admin-primary)' }}>shopping_cart</span>
          </div>
          <div style={{ fontSize: '32px', fontWeight: '700', color: 'var(--admin-primary)' }}>{counts.orders || 0}</div>
          <div style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-on-surface-variant)', marginTop: '8px' }}>
            Includes checkout orders persisted by `order-api`.
          </div>
        </div>

        <div style={{ backgroundColor: 'var(--admin-surface)', padding: '24px', borderRadius: '16px', border: '1px solid var(--admin-outline-variant)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
            <span style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-on-surface-variant)', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.15em' }}>Low Stock Items</span>
            <span className="material-symbols-outlined" style={{ color: 'var(--admin-error)' }}>warning</span>
          </div>
          <div style={{ fontSize: '32px', fontWeight: '700', color: 'var(--admin-primary)' }}>{overview?.inventory?.low_stock_items?.length || 0}</div>
          <div style={{ fontSize: 'var(--admin-font-body-sm)', color: 'var(--admin-on-surface-variant)', marginTop: '8px', display: 'flex', alignItems: 'center', gap: '4px' }}>
            Threshold uses stock value from integration overview.
          </div>
        </div>
      </div>

      <div style={{ backgroundColor: 'var(--admin-surface)', padding: '24px', borderRadius: '16px', border: '1px solid var(--admin-outline-variant)', minHeight: '300px' }}>
        {loading ? (
          <p style={{ color: 'var(--admin-on-surface-variant)' }}>Loading live dashboard...</p>
        ) : (
          <div style={{ display: 'grid', gap: '16px' }}>
            <h3 style={{ fontSize: '1.2rem' }}>Latest Integration Snapshot</h3>
            <p>Inventory reservations: {counts.inventory_reservations || 0}</p>
            <p>Invoices created: {counts.invoices || 0}</p>
            <p>CRM purchases synced: {counts.crm_purchases || 0}</p>
            {latest.order && (
              <p>
                Latest order #{latest.order.id} from {latest.order.customer_name} totaling {formatCurrency(latest.order.total_amount)}
              </p>
            )}
            {latest.invoice && (
              <Link to="/admin/sales" style={{ textDecoration: 'underline' }}>
                Open sales and invoice details
              </Link>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminDashboard;
